# Generated by Django 4.1.1 on 2023-01-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000)),
                ('sname', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('payment_id', models.CharField(max_length=1000)),
                ('Paid', models.BooleanField(default=False)),
            ],
        ),
    ]
